### ISSUE TITLE
distribution between the backend pods

### ISSUE THREAD

**Issue by movikbence** [Nordix/kahttp#1]
Hi

Can you please add a function which is similar to the output of the mconnect application?
mconnect -address <ip address:port> -nconn 200 -timeout 10s
Failed connects; 0
Failed reads; 0
mconnect-deployment-5d75b7c48c-jvpf4 50
mconnect-deployment-5d75b7c48c-lbrfn 50
mconnect-deployment-5d75b7c48c-rws6d 50
mconnect-deployment-5d75b7c48c-bh5f8 50

Thanks in advance.

**Comment by uablrek** [comment]
Included in release v0.3.
