### ISSUE TITLE
http-v1 requests with fault codes counts as succesful

### ISSUE THREAD

**Issue by movikbence** [Nordix/kahttp#4]
Hi
Could you make it possible to see the distribution between the pods when I am using an IP address instead of the hostname?

kahttp -address http://10.0.0.0 -monitor -host_stats | jq .
{
  "Started": "2019-05-16T11:47:51.002196261+02:00",
  "Duration": 9927841331,
  "Rate": 10,
  "Clients": 1,
  "Dials": 1,
  "FailedConnections": 0,
  "Sent": 100,
  "Received": 100,
  "Dropped": 0,
  "FailedConnects": 0
}

kahttp -address http://hostname -monitor -host_stats | jq .
{
  "Started": "2019-05-16T11:48:18.434265597+02:00",
  "Duration": 9937776212,
  "Rate": 10,
  "Clients": 1,
  "Dials": 1,
  "FailedConnections": 0,
  "Sent": 100,
  "Received": 100,
  "Dropped": 0,
  "FailedConnects": 0,
  "Hosts": {
    "kahttp-deployment-5c94487945-8gt7n": 25,
    "kahttp-deployment-5c94487945-9njn6": 25,
    "kahttp-deployment-5c94487945-gh5bn": 25,
    "kahttp-deployment-5c94487945-lzk2r": 25
  }
}

Thanks in advance.

**Comment by Zsolt-LazarZsolt** [comment]
Hi

In this case it looks more like our product kept sending 404 error to kahttp as answers. The server side accepted these answers as it were sent by kahttp clients. 
The only tell between a successful run and this is the missing stats.
Would it be possible to look only for successful answers only from kahttp clients?

Thank you for your answer in advance

**Comment by uablrek** [comment]
This is a bug. Calls not answered with an OK code (200) shall not be counted as succesful.

**Comment by uablrek** [comment]
A new stats counter is added; `NotOK` that counts all != 200 responses;
```
$ curl -s -D- http://localhost:9990/no
HTTP/1.0 404 Not Found
Content-type: text/html
Date: Sat, 26 Dec 2020 14:17:55 GMT
Connection: close

<HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD>
<BODY><H1>404 Not Found</H1>
The requested URL was not found
</BODY></HTML>
$ kahttp -address http://localhost:9990/no -timeout 3s | jq .
{
  "Started": "2020-12-26T15:15:33.964883773+01:00",
  "Duration": 2978245599,
  "Rate": 10,
  "Clients": 1,
  "Dials": 30,
  "FailedConnections": 0,
  "Sent": 30,
  "Received": 30,
  "Dropped": 0,
  "FailedConnects": 0,
  "NotOK": 30
}
```
In this run all requests returns "404 Not Found"
